skip_relocated = True # skip area RELOCATED
max_stacks = 1 # maximum number of stacks allowed
max_blocks = 7 # maximum number of blocks allowed in each stack
max_steps = 50 # maximum number of actions allowed in each episode
episode_max_reward = 1 # base reward for getting 1 block correct, cumulates with more blocks correct
reward_decay_factor = 1.2 # discount factor for subsequently correct blocks, the larger the faster the decay
action_cost = 1e-3 # cost for performing any action
max_assemblies = 20 # maximum number of assemblies for each area in the state representation
num_fibers = None # number of fibers in the brain, will be filled once env is created
num_areas = None # number of areas in the brain, will be filled once env is created
num_actions = None # number of actions, will be filled once env is created